site_name: ivy-rest Docs
site_url: https://nosejs.github.io/ivy-rest/
repo_url: https://github.com/nosejs/ivy-rest
edit_uri: https://github.com/nosejs/ivy-rest.git

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - django
  feature:
    tabs: true

nav:
  - 主页: index.md
  - 入门: starter-guide.md
  - 配置: configuring.md
  - 方法: methods.md
  - 复制元素: copying-elements.md
  - Observables: observables.md
  - 链接构建: url-building.md
  - 创建新方法: creating-new-methods.md
  - 自定义: custom.md
  - FAQ: faq.md
  - 服务框架: server-frameworks.md
